### PR TITLE
Add donate page and styling

### PR DESCRIPTION
**Pull request by TravisSperry**
Changes so far:
screen shot 2018-04-07 at 12 46 15 pm
screen shot 2018-04-07 at 12 46 25 pm

##Todos
- [ ] Add light inset drop shadow to card-header card-body and card-footer
- [ ] Increase border radius on card

### CODE REVIEW

**Comment by TravisSperry** [comment]
image

**Comment by TravisSperry** [comment]
image

**Comment by clicksave** [comment]
Woah! looks good here, i tried to get it up and running on my machine but the styles didn't carry over. 
🤔 I wonder what happened?



screen shot 2018-04-09 at 8 54 57 am

**Comment by TravisSperry** [comment]
Calvin-

Yeah I had some issues with the asset compilation/pipeline and was pushing broken things to master to test via Github Pages. But it’s all fixed now! Master should be clean and running smoothly and the branch that github fetches to display is ‘gh-pages’ not master now.

Thanks!

**Pull request merged**
